### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jjnether**
A proposed change to the paragraph summary giving the project status on the webpage

### CODE REVIEW

**Comment by croscas** [comment]
Thank you very much for the contribution! Maybe it would be useful to add a link to download the mod (nexus) and to the GitHub repository? Wdyt @RobbeBryssinck ?

**Comment by Dragonissa** [comment]
Why was the u removed in favourite? Its the original spelling of the word.

**Comment by croscas** [comment]
I guess it doesn't really matter
https://grammarist.com/spelling/favorite-favourite/

**Comment by jjnether** [comment]
@Dragonisser Must have been autocorrect :/  English spelling vs. American haha. my bad

**Pull request merged**
